# Andrea-MariaDB-FUNDING_PLATFORMS
github: # [ANDREA-MARIADB-2, ANDREAMARIADB, ANDIPANDI111, 777NINJAMUSIC]
patreon: # ANDREAMARIADB
open_collective: # ANDREAMARIADB
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # ANDREA-MARIADB
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
.Yyml
.yaml
.npm
